[Interface]
PrivateKey = FOd4I9ZAWkKBTw/RpeArP+4pRINrxPd2sRoT/zCo6zY=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
PublicKey = LTbI5UUe6XxL/N+qF9k8V/Vk+WEhLn7WXM7CFFT+VbQ=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 10.0.2.2:51820
