[Interface]
PrivateKey = EX8uS0qqoQyLSz+qUivuLsOeaNxvjHjpY1vsC5zF95E=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
PublicKey = Sys2ew7WXpSV9qTXpCQaEj6g6JyFspj5scqT4eHlXWk=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 10.0.2.2:51820
