[Interface]
PrivateKey = YMN0Z6U1yrzQcgEniP5SWT0S3O1o/5Jg5b9tcIkNFtA=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
PublicKey = me6ItLRBV0K+vUuv7tpmd5YQ2mvk0TM2xeXBmr2Ijac=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 10.0.2.2:51820
